# Generated by Django 4.1 on 2022-08-04 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=30)),
                ('inventory_weight', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_weight', models.IntegerField()),
                ('item_category', models.CharField(max_length=30)),
                ('item_quantity', models.IntegerField()),
                ('item_description', models.TextField()),
                ('item_essentialitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.essentialitem')),
                ('item_favorite_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.favoriteitem')),
                ('item_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('account_weight', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionData',
            fields=[
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('nutritiondata_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=30)),
                ('trip_start_point', models.FloatField()),
                ('trip_end_point', models.FloatField()),
                ('trip_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealplan_name', models.CharField(max_length=30)),
                ('mealplan_datetime', models.TextField()),
                ('mealplan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
                ('mealplan_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=30)),
                ('meal_datetime', models.CharField(max_length=30)),
                ('meal_mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mealplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
                ('location_elevation', models.IntegerField()),
                ('location_difficulty', models.IntegerField()),
                ('location_description', models.TextField()),
                ('location_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_account_id', to='api.trip')),
                ('location_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='favoriteitem_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
        migrations.AddField(
            model_name='essentialitem',
            name='essentialitem_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
    ]
