# Generated by Django 4.0.6 on 2022-08-15 02:59

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiker_first_name', models.CharField(max_length=24)),
                ('hiker_last_name', models.CharField(max_length=24)),
                ('hiker_physical_weight', models.FloatField()),
                ('hiker_age', models.SmallIntegerField()),
                ('hiker_height_inch', models.FloatField()),
                ('hiker_natural_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=100, unique=True)),
                ('trip_duration', models.PositiveSmallIntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('trip_hikers', models.ManyToManyField(blank=True, to='account.hiker')),
            ],
        ),
    ]
