# Generated by Django 4.0.6 on 2022-08-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=64)),
                ('category_slug', models.SlugField(default='self', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inventory_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=64)),
                ('item_weight', models.FloatField()),
                ('item_description', models.CharField(blank=True, max_length=128, null=True)),
                ('isEssential', models.BooleanField(default=False)),
                ('isFavorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('condition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_condition', models.CharField(choices=[('perfect', 'Perfect'), ('good', 'Good'), ('worn', 'Worn'), ('attention', 'Attention'), ('replace', 'Replace')], default='Perfect', max_length=9)),
                ('isConsumable', models.BooleanField(default=False)),
                ('item_percentage_remaining', models.CharField(choices=[('25%', '25'), ('50%', '50'), ('75%', '75'), ('100%', '100')], default='100', max_length=4)),
                ('item_expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_history_creation_date', models.DateTimeField(auto_now_add=True)),
                ('item_history_last_use_date', models.DateTimeField(auto_now=True)),
                ('item_history_last_use_condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('calories', models.PositiveSmallIntegerField()),
                ('protein', models.PositiveSmallIntegerField()),
                ('sugar', models.PositiveSmallIntegerField()),
            ],
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveSmallIntegerField()),
                ('isMultiple', models.BooleanField(default=False)),
                ('item_note', models.TextField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
