# Generated by Django 4.0.6 on 2022-08-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_id_alter_inventory_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(max_length=30),
        ),
    ]
